/**
 * TypeScript type definitions for Proactive Research Insights
 *
 * These types define the structure of insights generated by the
 * research advisor agent's proactive analysis mode.
 */

export interface ResearchArea {
  name: string;
  description: string;
  paper_count: number;
  significance: string;
}

export interface ResearchGap {
  gap_title: string;
  description: string;
  potential_value: string;
  exploration_steps: string;
}

export interface NextStep {
  action: string;
  rationale: string;
  estimated_time: string;
}

export interface SuggestedPaper {
  arxiv_id: string;
  title: string;
  authors: string[];
  abstract: string;
  published_date: string;
  url: string;
  categories: string[];
  suggested_because: string;
}

export interface KBContext {
  total_papers: number;
  categories: Record<string, number>;
  recent_activity: boolean;
}

export interface GenerationMetadata {
  timestamp: string;
  kb_papers_analyzed: number;
  conversation_history_used?: number;
  arxiv_papers_suggested: number;
  insights_quality: 'basic' | 'medium' | 'high';
  error?: string;
}

export interface ResearchInsights {
  research_areas: ResearchArea[];
  trending_topics: string[];
  research_gaps: ResearchGap[];
  next_steps: NextStep[];
  suggested_papers: SuggestedPaper[];
  kb_context: KBContext;
  generation_metadata: GenerationMetadata;
}

export interface InsightsLoadingState {
  isLoading: boolean;
  error: string | null;
  data: ResearchInsights | null;
  lastUpdated: string | null;
}
